#!/usr/bin/env python3
"""Generate ``english/en_item_menu.asm`` -- the item-menu routines and tables,
relocated into the expanded ROM (bank ``$2D``, mirror of JP/US bank ``$0D``).

The item menu is US code (its data tables are the US layout), pulled from
disassembly (``usdasm``) and mirror-placed at its ``+$200000`` address. In the
default (changes) form:

1. Redirect TRAMPOLINES -- four small stubs (``UpdateBottleMenu``,
   ``DrawAbilityText``, ``SetLiftText``, ``DrawEquippedYItem``) that ``PHK``/
   ``PLB`` set DBR=``$2D`` so the body can read its own bank tables, then
   ``JMP`` to the body. The stock US routine becomes ``EN_<name>_body`` and
   ends ``PLB`` / ``RTL`` (was ``RTS``) to restore the caller's DBR.
   The bank_0D landing pads (see ``base_edits.py``) ``JML`` here.
2. ``ItemMenuNameText_Mirror`` -- the US table has 2 rows but the item indexing
   wants JP's 4-row slot, so the US content is duplicated to fill it.
3. ``AbilityText`` -- US table, except rows 10-11 keep the JP tile values.

``--baseline`` emits the pure US relocation (no trampolines/edits).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import TYPE_CHECKING

from snes_assembly_parser import Line, Source

from graft import Placement, assemble, collect_names, en_namespace, mirror

if TYPE_CHECKING:
    from snes_assembly_parser import Segment

JPDASM = Path("../jpdasm")
USDASM = Path("../usdasm")
OUT = Path("en_item_menu.asm")

# The four repointed entry routines: each gets a DBR-setting trampoline;
# US body is renamed <name>_body and made to return long (RTL).
ENTRIES = (
    "UpdateBottleMenu",
    "DrawAbilityText",
    "SetLiftText",
    "DrawEquippedYItem",
)
TRAMPOLINE_ORG = 0x2DE100

# Bodies/data placed individually at their US mirror addr: (US block, EN
# name, return_long). Entry routines -> <name>_body; rest keep their names.
BODIES = (
    ("BottleMenuCursorPosition", "BottleMenuCursorPosition", False),
    ("UpdateBottleMenu", "UpdateBottleMenu_body", True),
    ("DrawMenuIcon", "DrawMenuIcon", False),
    ("DrawAbilityText", "DrawAbilityText_body", True),
    ("SetLiftText", "SetLiftText_body", True),
    ("DrawEquippedYItem", "DrawEquippedYItem_body", True),
)

# The name-text tables + icons + ability text form one contiguous US region;
# rendered together so the Mirror expansion cascades the rest forward exactly.
NAMETEXT = (
    "ItemMenuNameText_YItems",
    "ItemMenuNameText_Bottles",
    "ItemMenuNameText_Powder",
    "ItemMenuNameText_Flute",
    "ItemMenuNameText_Mirror",
    "ItemMenuNameText_Bow",
    "ItemIcons",
    "AbilityText",
)
# Separated from the region above by US code we skip; its own mirror addr.
CURSOR_TABLE = "MenuCursorPositions"

HEADER = (
    "; english/en_item_menu.asm -- item-menu routines + tables relocated to "
    "bank $2D (mirror of\n"
    "; US/JP bank $0D). generated by english/generate_item_menu.py from "
    "../usdasm + ../jpdasm.\n"
    "; Do not hand-edit. JP originals stay in bank_0D.asm as UNREACHABLE_*, "
    "with landing pads\n"
    "; that JML here; DBR trampolines let the relocated bodies read their own "
    "bank-$2D tables."
)


def return_long(segment: Segment) -> None:
    """Replace the final ``RTS`` with ``PLB``+``RTL`` (DBR restore).

    The body ran under DBR=$2D (set by its trampoline); ``PLB`` pops the
    caller's bank back before the long return. One byte longer than the stock
    ``RTS``, which fits the relocated body's slack.
    """
    for index in range(len(segment.lines) - 1, -1, -1):
        line = segment.lines[index]
        if line.opcode == "RTS":
            line.opcode, line.arguments = "PLB", []
            rtl = Line.from_line(f"#_{line.address:06X}: RTL")
            rtl.size = 1
            segment.lines.insert(index + 1, rtl)
            return
        if line.opcode is not None:
            break
    msg = "return_long: body does not end in RTS"
    raise ValueError(msg)


def trampolines() -> str:
    """The four DBR-setting redirect stubs, placed at ``TRAMPOLINE_ORG``.

    Bare names -- :func:`en_namespace` adds the ``EN_`` prefix uniformly.
    """
    lines: list[Line] = []
    pc = TRAMPOLINE_ORG
    for name in ENTRIES:
        lines.append(Line.from_line(f"{name}:"))
        for opcode in ("PHB", "PHK", "PLB"):
            lines.append(Line.from_line(f"#_{pc:06X}: {opcode}"))
            pc += 1
        lines.append(Line.from_line(f"#_{pc:06X}: JMP.w {name}_body"))
        pc += 3
    return "\n".join(str(line) for line in lines)


def sublabel_names(text: str, base_names: set[str]) -> set[str]:
    """Add ``Label_sublabel`` reference tokens to ``base_names``.

    A ``.sub`` sublabel under top-level ``Label:`` is referenced as
    ``Label_sub`` (e.g. ``ItemIcons_bottles``); :func:`collect_names` records
    only ``Label``, and the ``EN_`` rename's word boundary would skip the
    ``Label_sub`` form. Add each such token so it namespaces with its label.
    """
    names = set(base_names)
    for base in base_names:
        names |= set(re.findall(rf"\b{re.escape(base)}_\w+", text))
    return names


def duplicate_mirror(region: Segment) -> None:
    """Duplicate the US ``ItemMenuNameText_Mirror`` rows to JP's 4-row slot.

    The US table is 2 ``dw`` rows; the item indexing wants a 4-row slot, so the
    2 rows are copied once more right after themselves (byte-for-byte, so the
    following blocks cascade forward by the added $20 bytes).
    """
    start = next(
        i
        for i, line in enumerate(region.lines)
        if line.label and line.label.endswith("ItemMenuNameText_Mirror")
    )
    end = next(
        i
        for i in range(start + 1, len(region.lines))
        if region.lines[i].is_top_level_label
    )
    us_mirror_rows = 2  # US table is 2 dw rows; JP slot wants 4
    rows = [line for line in region.lines[start:end] if line.opcode == "dw"]
    if len(rows) != us_mirror_rows:
        msg = f"Mirror: expected {us_mirror_rows} US rows, found {len(rows)}"
        raise ValueError(msg)
    copies = [Line.from_line(str(row)) for row in rows]
    for copy, row in zip(copies, rows, strict=True):
        copy.size = row.size
    region.lines[end:end] = copies


def patch_ability_text(region: Segment, jp: Source) -> None:
    """Rows 10-11 of ``AbilityText`` keep the JP tile values (not US)."""
    jp_rows = [
        line.arguments
        for line in jp.block("AbilityText", comments=False).lines
        if line.opcode == "dw"
    ]
    row = 0
    inside = False
    for line in region.lines:
        if line.label and line.label.endswith("AbilityText"):
            inside = True
            continue
        if inside and line.is_top_level_label:
            break
        if inside and line.opcode == "dw":
            if row in (10, 11):
                line.arguments = jp_rows[row]
            row += 1


def build(
    *, changes: bool, jpdasm: Path = JPDASM, usdasm: Path = USDASM
) -> str:
    us = Source.from_path(usdasm / "bank_0D.asm")
    jp = Source.from_path(jpdasm / "bank_0D.asm")

    rendered: list[tuple[int, str]] = []

    # ---- redirect trampolines (changes only) ----
    if changes:
        rendered.append((TRAMPOLINE_ORG, trampolines()))

    # ---- bodies/data, each at its US mirror address ----
    for us_name, en_name, long_return in BODIES:
        body = us.block(us_name, comments=False)
        start = body.start_address
        if start is None:
            msg = f"{us_name} has no address anchor"
            raise ValueError(msg)
        if changes and long_return:
            return_long(body)
        if en_name != us_name:
            body.lines[0].label = en_name  # rename the routine label
        rendered.append((mirror(start), body.render(mirror(start))))

    # ---- contiguous name-text region (Mirror expansion cascades rest) ----
    region = us.concat([*NAMETEXT])
    region_start = region.start_address
    if region_start is None:
        msg = "name-text region has no address anchor"
        raise ValueError(msg)
    if changes:
        duplicate_mirror(region)
        patch_ability_text(region, jp)
    rendered.append(
        (mirror(region_start), region.render(mirror(region_start)))
    )

    # ---- cursor table: US mirror shifted by the Mirror expansion ($20) ----
    cursor = us.block(CURSOR_TABLE, comments=False)
    cursor_start = cursor.start_address
    if cursor_start is None:
        msg = f"{CURSOR_TABLE} has no address anchor"
        raise ValueError(msg)
    shift = 0x20 if changes else 0  # Mirror grew by $20 (2 rows)
    cursor_org = mirror(cursor_start) + shift
    rendered.append((cursor_org, cursor.render(cursor_org)))

    # ---- one global EN_ namespace across all pieces (+ sublabel refs) ----
    whole = "\n".join(text for _, text in rendered)
    names = sublabel_names(whole, collect_names(whole))
    placements = [
        Placement(org, en_namespace(text, names), f"item-menu @ ${org:06X}.")
        for org, text in rendered
    ]
    return assemble(HEADER, placements)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        action="store_true",
        help="emit the pure US relocation with no trampolines or edits",
    )
    parser.add_argument("--jpdasm", type=Path, default=JPDASM)
    parser.add_argument("--usdasm", type=Path, default=USDASM)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        build(
            changes=not args.baseline, jpdasm=args.jpdasm, usdasm=args.usdasm
        )
    )
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
