#!/usr/bin/env python3
"""Generate ``english/us_bank00.asm`` -- the one bank-$00 routine the English
build relocates into the expanded ROM.

``TransferFontToVRAM`` is pulled verbatim from the JP disassembly
(``jpdasm``), mirror-placed at its ``+$200000`` address (``$00E596`` ->
``$20E596``), and given the ``EN_`` namespace. In the default (changes) form
its three font-source operands are repointed at our ``TheFont`` (font.2bpp) so
it uploads the US 2bpp font to VRAM ``$E000`` instead of JP's ``$7E2000`` VWF
buffer; the byte length is unchanged, so nothing shifts. ``--baseline`` emits
the pure JP
relocation with no edits and no bare hook alias -- the clean base for a diff.

The JP original stays in ``bank_00.asm`` as ``UNREACHABLE_TransferFontToVRAM``
(freed by ``base_edits.py``); the bare ``TransferFontToVRAM`` alias here claims
the name so unmodified JP ``JSL`` callers resolve to our copy.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from snes_assembly_parser import Assembly, note

from graft import Relocation, mirror

JPDASM = Path("../jpdasm")  # default JP disassembly (override with --jpdasm)
OUT = Path("us_bank00.asm")

ROOT = "TransferFontToVRAM"
HOOKS = frozenset({ROOT})
SHARED = frozenset({"TheFont", "TheFont_end"})  # our font, uploaded here

# The three font-source operands, repointed from JP's $7E2000 VWF buffer to our
# plain 2bpp TheFont. Each replacement is the same byte width as the original,
# so the routine stays byte-identical in length.
FONT_EDITS = (
    ("LDA.b #$7E", "LDA.b #TheFont>>16"),  # source bank
    ("LDA.w #$7E2000", "LDA.w #TheFont"),  # source address
    ("LDX.w #$0FFF", "LDX.w #(TheFont_end-TheFont)/2-1"),  # word count - 1
)

HEADER = (
    "; english/us_bank00.asm -- bank-$00 TransferFontToVRAM relocated to its "
    "+$200000 mirror\n"
    "; (JP $00E596 -> $20E596). generated by english/generate_bank00.py from "
    "../jpdasm. Do not\n"
    "; hand-edit. The JP original stays in bank_00.asm as UNREACHABLE_*; JSL "
    "callers auto-resolve\n"
    "; here. In the default form the font upload is repointed at TheFont "
    "(font.2bpp, VRAM $E000)."
)

BODY_NOTE = (
    "; [ENG-GFX] Uploads TheFont (font.2bpp) to VRAM $E000 -- the US form "
    "(JP uploaded a $7E2000 VWF buffer)."
)


def build(*, changes: bool, jpdasm: Path = JPDASM) -> Relocation:
    bank00 = Assembly.from_path(jpdasm / "bank_00.asm")
    routine = bank00.extract([ROOT], recursive=True, external=SHARED)
    start = routine.start_address
    if start is None:
        msg = f"{ROOT} has no address anchor"
        raise ValueError(msg)
    if changes:
        for old, new in FONT_EDITS:
            routine.replace(old, new, count=1)
        routine.lines.insert(0, note(BODY_NOTE))

    relocation = Relocation(
        HEADER, hooks=HOOKS if changes else frozenset(), shared=SHARED
    )
    relocation.place(
        routine,
        mirror(start),
        "bank-$00 TransferFontToVRAM (mirror of JP $00E596).",
    )
    return relocation


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        action="store_true",
        help="emit the pure JP relocation with no edits or hook alias",
    )
    parser.add_argument(
        "--jpdasm",
        type=Path,
        default=JPDASM,
        help=f"JP disassembly to pull from (default: {JPDASM})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT,
        help=f"where to write us_bank00.asm (default: {OUT})",
    )
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        build(changes=not args.baseline, jpdasm=args.jpdasm).render()
    )
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
