#!/usr/bin/env python3
"""Generate ``bank_26.asm`` -- the US menu/HUD + file-select graphics sheets,
relocated into the expanded ROM (bank ``$26``).

These are the three graphics sheets that differ JP<->US (the JP kana vs US
Latin menu/file-select font, ``GFX_DC``/``GFX_DD``, and the US file-select
"linoleum" background, ``GFX_39``). Like the VWF font, they are *binary US-ROM
data* -- the disassembly stores them as ``incbin`` of compressed byte slices,
so we do the same: ``extract_english_assets.py`` rips the slices out of the US
ROM into ``english/`` and each sheet ``incbin``\\ s its slice. Each keeps its
bare JP name (``base_edits.py`` frees the JP originals -- ``GFX_DC``/``GFX_DD``
in bank_18, ``GFX_39`` in bank_13) so the game's own ``GFXSheetPointers`` /
tileset loader resolve to the US art, plus an ``EN_`` alias for uniformity.

``--baseline`` drops the bare-name aliases (the US sheets sit here
unreferenced, the JP originals stay wired) -- a no-op relocation for a diff.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from graft import Relocation

OUT = Path("bank_26.asm")
GFX_ORG = 0x268000

# (JP sheet name, its US-ROM slice as extracted into english/). Packed in this
# order from $268000; referenced by symbol, so the exact address is asar's job.
SHEETS = (
    ("GFX_DC", "gfx_dc.2bppc"),  # US menu / file-select font sheet ($69)
    ("GFX_DD", "gfx_dd.2bppc"),  # US menu / file-select font sheet ($6A)
    ("GFX_39", "gfx_39.3bppc"),  # US file-select "linoleum" background ($39)
)
HOOKS = frozenset(name for name, _ in SHEETS)

HEADER = (
    "; bank_26.asm -- US menu/HUD + file-select graphics sheets, relocated to "
    "bank $26.\n"
    "; generated by english/generate_gfx.py; do not hand-edit. The sheets are "
    "US-ROM byte\n"
    "; slices (english/*.2bppc/.3bppc, via extract_english_assets.py); each "
    "claims its freed\n"
    "; JP name so the game's own GFXSheetPointers / tileset loader resolve to "
    "the US art."
)


def build(*, changes: bool) -> Relocation:
    body = "\n\n".join(
        f'{name}:\n    incbin "english/{asset}"' for name, asset in SHEETS
    )
    relocation = Relocation(HEADER, hooks=HOOKS if changes else frozenset())
    relocation.place(
        body, GFX_ORG, "US graphics sheets (menu/HUD + file-select)."
    )
    return relocation


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", action="store_true")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    args.out.write_text(build(changes=not args.baseline).render())
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
