#!/usr/bin/env python3
"""Generate ``english/en_credits.asm`` -- the credits reader and tables,
relocated into the expanded ROM.

The credits code is pulled from the JP disassembly (``jpdasm`` bank ``$0E``)
and mirror-placed at its ``+$200000`` address (bank ``$0E`` -> ``$2E``), in
three contiguous groups (the JP source interleaves them with credits code we do
not relocate, so each group gets its own ``org``). In the default (changes)
form two small edits make it English:

1. ``Credits_CharacterToTile`` -- the 159-entry glyph map is replaced with the
   US table (from ``usdasm``), so credits text renders with the US Latin font
   instead of JP kana. Same length, so nothing shifts.
2. Each reader ends ``RTL`` instead of the JP ``RTS`` -- they are now reached
   across banks via the ``bank_0E`` landing pads (see ``base_edits.py``), whose
   ``JML`` needs a long return.

``--baseline`` emits the pure JP relocation (no edits, no bare hook aliases).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import TYPE_CHECKING

from snes_assembly_parser import Block, Pool, Source

from graft import Placement, assemble, collect_names, en_namespace, mirror

if TYPE_CHECKING:
    from snes_assembly_parser import Segment

JPDASM = Path("../jpdasm")
USDASM = Path("../usdasm")
OUT = Path("en_credits.asm")

# The three contiguous groups of credits blocks/pools, in source order. Each is
# concatenated on its own and placed at its group's +$200000 mirror address.
# ``us_glyphs`` names the leading blocks/pools whose dw glyph-tile values are
# taken from the US font layout (same length as JP, so byte-neutral); the JP
# text data that follows (CreditsTextLine) is kept as-is.
GROUPS: tuple[tuple[tuple[Block | Pool, ...], tuple[str, ...]], ...] = (
    (
        (
            Block("Credits_CharacterToTile"),
            Block("CreditsBlankFillTile"),
            Pool("CreditsTextLine"),
        ),
        ("Credits_CharacterToTile", "CreditsBlankFillTile"),
    ),
    (
        (
            Pool("Credits_AddNextAttribution"),
            Block("Credits_AddNextAttribution"),
        ),
        ("Credits_AddNextAttribution",),
    ),
    (
        (
            Pool("Credits_AddEndingSequenceText"),
            Block("Credits_AddEndingSequenceText"),
        ),
        (),  # ending-sequence tilemap keeps JP palette attributes as-is
    ),
)
# JP readers reached across banks -> must return long. Unlike the text engine,
# these keep ONLY their EN_ names here: base_edits.py puts a landing pad under
# each bare name in bank_0E, so the bare alias must NOT be redefined here.
READERS = ("Credits_AddNextAttribution", "Credits_AddEndingSequenceText")
_POOL_REF = re.compile(r"^[ \t]*pool[ \t]+([A-Za-z_]\w*)", re.MULTILINE)

HEADER = (
    "; english/en_credits.asm -- credits reader + tables relocated to bank "
    "$2E (mirror of JP\n"
    "; bank $0E). generated by english/generate_credits.py from ../jpdasm + "
    "../usdasm. Do not\n"
    "; hand-edit. In the default form the glyph map is the US table and the "
    "readers return long."
)


def us_glyph_values(us: Source, names: tuple[str, ...]) -> list[list[str]]:
    """The dw operand lists of the named US blocks/pools, in order.

    A name is a block, a pool, or (when both exist) the pool's data followed by
    the block's -- matching how ``Source.concat`` lays them out.
    """
    values: list[list[str]] = []
    for name in names:
        segments = []
        if name in us.pools:
            segments.append(us.pool(name, comments=False))
        if name in us.labels:
            segments.append(us.block(name, comments=False))
        for segment in segments:
            values += [
                line.arguments for line in segment.lines if line.opcode == "dw"
            ]
    return values


def splice_us_glyphs(group: Segment, values: list[list[str]]) -> None:
    """Overwrite the group's leading ``dw`` values with the US glyph tiles.

    The glyph blocks come first in each group and are the same length in JP and
    US, so only the leading operand values change (byte-neutral); any JP text
    data further down is left untouched.
    """
    index = 0
    for line in group.lines:
        if line.opcode == "dw" and index < len(values):
            line.arguments = values[index]
            index += 1
    if index != len(values):
        msg = f"glyph splice: wrote {index} of {len(values)} entries"
        raise ValueError(msg)


def return_long(group: Segment) -> None:
    """Turn the group's final ``RTS`` into ``RTL`` (same size)."""
    for line in reversed(group.lines):
        if line.opcode == "RTS":
            line.opcode = "RTL"
            return
        if line.opcode is not None:
            break
    msg = "return_long: group does not end in RTS"
    raise ValueError(msg)


def pool_qualified_names(text: str, base_names: set[str]) -> set[str]:
    """Add ``Pool_sublabel`` reference names to ``base_names``.

    An asar ``pool Foo`` exposes its ``.bar`` sublabel as ``Foo_bar`` at the
    reference site; :func:`collect_names` records only the pool base ``Foo``,
    so the ``EN_`` rename would miss those refs. Find every ``Foo_...`` token
    for a pool ``Foo`` and add it so it is namespaced with its pool.
    """
    names = set(base_names)
    for pool in _POOL_REF.findall(text):
        names |= set(re.findall(rf"\b{re.escape(pool)}_\w+", text))
    return names


def build(
    *, changes: bool, jpdasm: Path = JPDASM, usdasm: Path = USDASM
) -> str:
    jp = Source.from_path(jpdasm / "bank_0E.asm")
    us = Source.from_path(usdasm / "bank_0E.asm")

    rendered: list[tuple[int, str]] = []
    for blocks, glyph_blocks in GROUPS:
        group = jp.concat(list(blocks))
        start = group.start_address
        if start is None:
            msg = f"group {blocks[0].name} has no address anchor"
            raise ValueError(msg)
        if changes:
            splice_us_glyphs(group, us_glyph_values(us, glyph_blocks))
            if any(b.name in READERS for b in blocks):
                return_long(group)
        rendered.append((mirror(start), group.render(mirror(start))))

    # One global name set so a reference in a reader group resolves to its
    # definition in the data group (same as the text engine's namespacing).
    # Pools are defined in one group and referenced in another, so gather the
    # Pool_sublabel names across ALL groups' text at once.
    whole = "\n".join(text for _, text in rendered)
    names = pool_qualified_names(whole, collect_names(whole))
    # Credits use landing pads, so the bare names live in bank_0E, not here.
    hooks: frozenset[str] = frozenset()
    placements = [
        Placement(
            org,
            en_namespace(text, names, hooks=hooks),
            f"credits group at mirror of JP ${org - 0x200000:06X}.",
        )
        for org, text in rendered
    ]
    return assemble(HEADER, placements)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        action="store_true",
        help="emit the pure JP relocation with no edits or hook aliases",
    )
    parser.add_argument("--jpdasm", type=Path, default=JPDASM)
    parser.add_argument("--usdasm", type=Path, default=USDASM)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        build(
            changes=not args.baseline, jpdasm=args.jpdasm, usdasm=args.usdasm
        )
    )
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
