#!/usr/bin/env python3
"""Generate ``english/en_credits.asm`` -- the credits reader and tables,
relocated into the expanded ROM.

The credits code is pulled from the JP disassembly (``jpdasm`` bank ``$0E``)
and mirror-placed at its ``+$200000`` address (bank ``$0E`` -> ``$2E``), in
three contiguous groups (the JP source interleaves them with credits code we do
not relocate, so each group gets its own ``org``). In the default (changes)
form two small edits make it English:

1. ``Credits_CharacterToTile`` -- the 159-entry glyph map is replaced with the
   US table (from ``usdasm``), so credits text renders with the US Latin font
   instead of JP kana. Same length, so nothing shifts.
2. Each reader ends ``RTL`` instead of the JP ``RTS`` -- they are now reached
   across banks via the ``bank_0E`` landing pads (see ``base_edits.py``), whose
   ``JML`` needs a long return.

``--baseline`` emits the pure JP relocation (no edits, no bare hook aliases).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from snes_assembly_parser import Assembly, Block, Pool

from graft import Relocation, mirror

JPDASM = Path("../jpdasm")
USDASM = Path("../usdasm")
OUT = Path("en_credits.asm")

# The three contiguous groups of credits blocks/pools, in source order. Each is
# concatenated on its own and placed at its group's +$200000 mirror address.
# ``us_glyphs`` names the leading blocks/pools whose dw glyph-tile values are
# taken from the US font layout (same length as JP, so byte-neutral); the JP
# text data that follows (CreditsTextLine) is kept as-is.
GROUPS: tuple[tuple[tuple[Block | Pool, ...], tuple[str, ...]], ...] = (
    (
        (
            Block("Credits_CharacterToTile"),
            Block("CreditsBlankFillTile"),
            Pool("CreditsTextLine"),
        ),
        ("Credits_CharacterToTile", "CreditsBlankFillTile"),
    ),
    (
        (
            Pool("Credits_AddNextAttribution"),
            Block("Credits_AddNextAttribution"),
        ),
        ("Credits_AddNextAttribution",),
    ),
    (
        (
            Pool("Credits_AddEndingSequenceText"),
            Block("Credits_AddEndingSequenceText"),
        ),
        (),  # ending-sequence tilemap keeps JP palette attributes as-is
    ),
)
# JP readers reached across banks -> must return long. Unlike the text engine,
# these keep ONLY their EN_ names here: base_edits.py puts a landing pad under
# each bare name in bank_0E, so the bare alias must NOT be redefined here.
READERS = ("Credits_AddNextAttribution", "Credits_AddEndingSequenceText")

HEADER = (
    "; english/en_credits.asm -- credits reader + tables relocated to bank "
    "$2E (mirror of JP\n"
    "; bank $0E). generated by english/generate_credits.py from ../jpdasm + "
    "../usdasm. Do not\n"
    "; hand-edit. In the default form the glyph map is the US table and the "
    "readers return long."
)


def us_glyph_values(
    us_bank: Assembly, names: tuple[str, ...]
) -> list[list[str]]:
    """The dw operand lists of the named US blocks/pools, in order.

    A name is a block, a pool, or (when both exist) the pool's data followed by
    the block's -- matching how ``Assembly.concat`` lays them out.
    """
    values: list[list[str]] = []
    for name in names:
        segments = []
        if name in us_bank.pools:
            segments.append(us_bank.pool(name, comments=False))
        if name in us_bank.labels:
            segments.append(us_bank.function(name, comments=False))
        for segment in segments:
            values += [
                line.arguments for line in segment.lines if line.opcode == "dw"
            ]
    return values


def splice_us_glyphs(group: Assembly, values: list[list[str]]) -> None:
    """Overwrite the group's leading ``dw`` values with the US glyph tiles.

    The glyph blocks come first in each group and are the same length in JP and
    US, so only the leading operand values change (byte-neutral); any JP text
    data further down is left untouched.
    """
    index = 0
    for line in group.lines:
        if line.opcode == "dw" and index < len(values):
            line.arguments = values[index]
            index += 1
    if index != len(values):
        msg = f"glyph splice: wrote {index} of {len(values)} entries"
        raise ValueError(msg)


def return_long(group: Assembly) -> None:
    """Turn the group's final ``RTS`` into ``RTL`` (same size)."""
    for line in reversed(group.lines):
        if line.opcode == "RTS":
            line.opcode = "RTL"
            return
        if line.opcode is not None:
            break
    msg = "return_long: group does not end in RTS"
    raise ValueError(msg)


def build(
    *, changes: bool, jpdasm: Path = JPDASM, usdasm: Path = USDASM
) -> Relocation:
    jp_bank = Assembly.from_path(jpdasm / "bank_0E.asm")
    us_bank = Assembly.from_path(usdasm / "bank_0E.asm")

    # Namespaced globally across all groups so a reference in a reader group
    # resolves to its definition in a data group; credits use landing pads, so
    # the bare hook names live in bank_0E, not here (no hooks/shared).
    relocation = Relocation(HEADER)
    for blocks, glyph_blocks in GROUPS:
        group = jp_bank.concat(list(blocks))
        start = group.start_address
        if start is None:
            msg = f"group {blocks[0].name} has no address anchor"
            raise ValueError(msg)
        if changes:
            splice_us_glyphs(group, us_glyph_values(us_bank, glyph_blocks))
            if any(block.name in READERS for block in blocks):
                return_long(group)
        relocation.place(
            group,
            mirror(start),
            f"credits group at mirror of JP ${start:06X}.",
        )
    return relocation


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        action="store_true",
        help="emit the pure JP relocation with no edits or hook aliases",
    )
    parser.add_argument("--jpdasm", type=Path, default=JPDASM)
    parser.add_argument("--usdasm", type=Path, default=USDASM)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        build(
            changes=not args.baseline, jpdasm=args.jpdasm, usdasm=args.usdasm
        ).render()
    )
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
