#!/usr/bin/env python3
"""Generate ``bank_27.asm`` -- the file-select US palette overlay, relocated
into the expanded ROM (bank ``$27``).

The file-select composes its CGRAM from the game's own shared palette-load
routines; almost every row is byte-identical JP<->US, so the native loads
already produce the right US colors on the JP ROM. Exactly four 7-color
palettes (CGRAM rows 5, 7, 9, 11) plus one stray color (row 14 color 15)
differ. Those four palettes are *US-ROM data* -- plain slices of the US ROM's
``PaletteData`` table -- so ``extract_english_assets.py`` rips them into
``english/usfs_pal.bin`` and ``USFS_Palette`` ``incbin``\\ s them.

The one piece of graft glue is ``USFS_PaletteLoadForFileSelect``: it runs the
stock US ``PaletteLoadForFileSelect`` and then overlays those four US palettes
into both CGRAM buffers, once per (re)init. ``generate_menu`` repoints the one
``JSL PaletteLoadForFileSelect`` (a byte-neutral operand swap) at this wrapper,
so the ported file-select code stays byte-for-byte the US original.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from graft import Relocation

OUT = Path("bank_27.asm")
PALETTE_ORG = 0x278000

# CGRAM color N of row R is buffer byte 2*(R*16+N); PaletteLoadForFileSelect
# writes both the compose buffer ($7EC300) and the NMI-DMA source ($7EC500), so
# the overlay writes both. Rows 5/7/9/11 colors 1-7 (offset $A2/$E2/$122/$162)
# come from USFS_Palette in that order; row 14 color 15 ($1DE) is forced black.
BODY = """\
USFS_PaletteLoadForFileSelect:
    JSL PaletteLoadForFileSelect    ; stock US load (JP palette for FS rows)
    PHP                             ; preserve caller's processor mode (M/X)
    REP #$30                        ; 16-bit A AND index
    PHB
    PHK
    PLB
    LDX.w #$0000
.row5
    LDA.l USFS_Palette+$00,X
    STA.l $7EC3A2,X                 ; buffer A (compose)
    STA.l $7EC5A2,X                 ; buffer B (NMI DMA source)
    INX
    INX
    CPX.w #$000E
    BNE .row5
    LDX.w #$0000
.row7
    LDA.l USFS_Palette+$0E,X
    STA.l $7EC3E2,X
    STA.l $7EC5E2,X
    INX
    INX
    CPX.w #$000E
    BNE .row7
    LDX.w #$0000
.row9
    LDA.l USFS_Palette+$1C,X
    STA.l $7EC422,X
    STA.l $7EC622,X
    INX
    INX
    CPX.w #$000E
    BNE .row9
    LDX.w #$0000
.row11
    LDA.l USFS_Palette+$2A,X
    STA.l $7EC462,X
    STA.l $7EC662,X
    INX
    INX
    CPX.w #$000E
    BNE .row11
    LDA.w #$0000                    ; row 14 color 15 -> black (US)
    STA.l $7EC4DE
    STA.l $7EC6DE
    PLB
    PLP
    RTL

; Four US file-select palettes (colors 1-7 each), CGRAM-row order 5, 7, 9, 11.
USFS_Palette:
    incbin "english/usfs_pal.bin\""""

HEADER = (
    "; bank_27.asm -- file-select US palette overlay, relocated to bank $27.\n"
    "; generated by english/generate_fs_palette.py; do not hand-edit. The "
    "four US palettes are\n"
    "; US-ROM PaletteData slices (english/usfs_pal.bin); the overlay wrapper "
    "is reached via the\n"
    "; one repointed JSL in generate_menu (ReinitializeFileSelectGraphics)."
)


def build(*, changes: bool) -> Relocation:  # noqa: ARG001 (uniform signature)
    relocation = Relocation(HEADER)
    relocation.place(
        BODY,
        PALETTE_ORG,
        "file-select US palette overlay + data.",
        namespace=False,
    )
    return relocation


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", action="store_true")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()
    args.out.write_text(build(changes=not args.baseline).render())
    mode = "baseline" if args.baseline else "with changes"
    print(f"wrote {args.out} ({mode})")


if __name__ == "__main__":
    main()
